import {describe,expect,it} from 'vitest';
import {createDefaultProject} from '../../project/defaults';
import {buildCapabilityManifest} from '../capabilities/buildCapabilityManifest';
import {applyAIPlan} from '../executor/applyAIPlan';
import {MockAIPlanner} from './MockAIPlanner';
const planner=new MockAIPlanner(),base={project:createDefaultProject(),capabilities:buildCapabilityManifest()};
describe('MockAIPlanner',()=>{
 it('selects coffee template',async()=>expect((await planner.plan({...base,message:'Сделай приложение кофейни'})).actions).toContainEqual({type:'create_from_template',payload:{templateId:'coffee_house'}}));
 it('configures a six-coffee reward',async()=>expect((await planner.plan({...base,message:'6 кофе бесплатно'})).actions).toContainEqual({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{goal:6,reward:'Бесплатный кофе'}}}));
 it.each([['как настоящую карточку','punch_card'],['Покажи прогресс дорожкой','journey_path'],['сделай минималистично','minimal_counter'],['хочу коллекцию','collection_gallery'],['обычная сетка','classic_grid']])('maps %s to %s',async(message,visualVariant)=>expect((await planner.plan({...base,message})).actions).toContainEqual({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{presentation:{visualVariant}}}}));
 it('changes only presentation for a design request',async()=>{const project=createDefaultProject();const module=project.modules.find(m=>m.type==='loyalty_passport')!;module.config={...module.config as object,name:'Ремонт+',goal:5,reward:'Скидка 30%',balance:3};const before=structuredClone(module.config) as Record<string,unknown>;const plan=await planner.plan({project,capabilities:base.capabilities,message:'Сделай паспорт как настоящую карточку'});const next=applyAIPlan(project,plan);const after=next.modules.find(m=>m.type==='loyalty_passport')!.config as Record<string,unknown>;expect({name:after.name,goal:after.goal,reward:after.reward,balance:after.balance}).toEqual({name:before.name,goal:before.goal,reward:before.reward,balance:before.balance});expect((after.presentation as {visualVariant:string}).visualVariant).toBe('punch_card');expect(next.draftRevision).toBe(project.draftRevision+1)});
 it('reports unavailable booking without inventing a module',async()=>{const p=await planner.plan({...base,message:'Добавь онлайн-запись'});expect(p.missingInformation[0]).toContain('недоступна');expect(p.actions.some(a=>'moduleType'in a.payload&&a.payload.moduleType==='booking')).toBe(false)});
 it('does not replace an existing app when user asks to add Shop',async()=>{const p=await planner.plan({...base,message:'Добавь магазин и корзину'});expect(p.actions.some(a=>a.type==='create_from_template')).toBe(false);expect(p.missingInformation.join(' ')).toContain('Интернет-магазин')});
 it('can create a Store foundation when explicitly creating a new store app',async()=>{const p=await planner.plan({...base,message:'Сделай приложение магазина'});expect(p.actions).toContainEqual({type:'create_from_template',payload:{templateId:'store'}})});
});

describe('Passport composition',()=>{
 const presentation=async(message:string,project=base.project)=>{const plan=await planner.plan({project:structuredClone(project),capabilities:base.capabilities,message});return plan.actions.filter(a=>a.type==='patch_module_config'&&a.payload.moduleType==='loyalty_passport')};
 it.each([['квадратные отметки',{stampShape:'square'}],['крупная шапка',{headerMode:'hero'}],['4 колонки',{columns:4}],['кольцо прогресса',{progressMode:'ring'}]])('creates smallest patch for %s',async(message,expected)=>expect(await presentation(message)).toEqual([{type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{presentation:expected}}}]));
 it('composes a vertical four-column collection atomically',async()=>expect(await presentation('Сделай вертикальную коллекцию в 4 колонки')).toEqual([{type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{presentation:{visualVariant:'collection_gallery',columns:4,imageAspect:'portrait'}}}}]));
 it('composes the card request atomically',async()=>expect(await presentation('как настоящую карточку, квадратные отметки, крупная шапка, без полосы прогресса')).toEqual([{type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{presentation:{visualVariant:'punch_card',stampShape:'square',headerMode:'hero',progressMode:'counter'}}}}]));
 it('does not emit columns for minimal counter',async()=>{const project=structuredClone(base.project);const module=project.modules.find(m=>m.type==='loyalty_passport')!;(module.config as any).presentation.visualVariant='minimal_counter';const plan=await planner.plan({project,capabilities:base.capabilities,message:'4 колонки'});expect(plan.actions).toEqual([]);expect(plan.missingInformation.join(' ')).toContain('не использует');});
});
