import {describe,expect,it} from 'vitest';import {describeAIAction} from './describeAIAction';
describe('describeAIAction',()=>{it('describes only actual business and design patch values in human terms',()=>expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{goal:8,reward:'Скидка 20%',presentation:{visualVariant:'punch_card',stampShape:'square'}}}})).toEqual([{label:'Цель',value:'8'},{label:'Награда',value:'Скидка 20%'},{label:'Вид',value:'Карта с печатями'},{label:'Отметки',value:'Квадратные'}]));});
it('summarizes stamp patches without raw JSON or excessive rows',()=>{expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':{title:'Покраска'}}}}})).toEqual([{label:'Этап 2',value:'Покраска'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'5':{iconKey:'gift'}}}}})).toEqual([{label:'Этап 5 · Иконка',value:'Подарок'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'1':{title:'Приёмка'},'2':{title:'Диагностика'},'3':{title:'Ремонт'},'4':{title:'Готово'}}}}})).toEqual([{label:'Этапы',value:'настроено 4: Приёмка · Диагностика · Ремонт · …'}]);});
it('makes partial and whole stamp resets explicit',()=>{expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':{title:null}}}}})).toEqual([{label:'Этап 2 · Название',value:'По умолчанию'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':{iconKey:null}}}}})).toEqual([{label:'Этап 2 · Иконка',value:'По умолчанию'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':null}}}})).toEqual([{label:'Этап 2',value:'Сброшен'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':{title:'Покраска',iconKey:null}}}}})).toEqual([{label:'Этап 2',value:'Покраска'},{label:'Этап 2 · Иконка',value:'По умолчанию'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':null,'3':{title:'Ремонт'}}}}})).toEqual([{label:'Этапы',value:'2 изменения: этап 2 сброшен · Ремонт'}]);});

describe('cover proposal descriptions',()=>{
 it('describes cover set and clear from catalog labels',()=>{expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'5':{cover:{source:'catalog',assetId:'gift-box'}}}}}})).toEqual([{label:'Этап 5 · Обложка',value:'Подарок'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'5':{cover:null}}}}})).toEqual([{label:'Этап 5 · Обложка',value:'По умолчанию'}]);});
 it('describes mixed fields and summarizes multiple positions',()=>{expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'2':{title:'Покраска',cover:{source:'catalog',assetId:'repair-tools'}}}}}})).toEqual([{label:'Этап 2',value:'Покраска'},{label:'Этап 2 · Обложка',value:'Инструменты'}]);expect(describeAIAction({type:'patch_module_config',payload:{moduleType:'loyalty_passport',patch:{stampContent:{'1':{title:'Приёмка'},'2':{cover:{source:'catalog',assetId:'gift-box'}},'3':null}}}})).toEqual([{label:'Этапы',value:'3 изменения: Приёмка · этап 2: Подарок · этап 3 сброшен'}]);});
});
