import { describe, expect, it } from 'vitest';
import { createMediaRouteDeps, handleMediaDiagnostics, handleMediaGet, handleMediaUpload, type MediaBucket } from './routes';
const mediaId='m1_abcdefghijklmnop_qrstuvwxyzABCDEF_123e4567-e89b-42d3-a456-426614174000';
const structuralJPEG=new Uint8Array([0xff,0xd8,0xff,0xc0,0,17,8,0,2,0,3,3,1,0x11,0,2,0x11,0,3,0x11,0,0xff,0xda,0,8,1,1,0,0,63,0,1,2,0xff,0xd9]);
class FakeBucket implements MediaBucket {
  objects=new Map<string,{bytes:ArrayBuffer;options?:any;etag?:string}>(); puts:string[]=[]; lists:{prefix:string;limit?:number}[]=[]; fail?:'list'|'put'|'get';
  async put(key:string,value:ArrayBuffer,options?:any){if(this.fail==='put')throw new Error('private r2 detail');this.puts.push(key);this.objects.set(key,{bytes:value,options});}
  async get(key:string){if(this.fail==='get')throw new Error('private r2 detail');const value=this.objects.get(key);return value?{body:value.bytes,httpEtag:value.etag}:null;}
  async list(options:{prefix:string;limit?:number}){if(this.fail==='list')throw new Error('private r2 detail');this.lists.push(options);return {objects:[...this.objects.keys()].filter(key=>key.startsWith(options.prefix)).slice(0,options.limit).map(key=>({key}))};}
}
const deps=(overrides:Parameters<typeof createMediaRouteDeps>[0]={})=>createMediaRouteDeps({validateAuth:async()=>({userId:'123456789'}),now:()=>1_000,createIdentity:async()=>({ownerScope:'abcdefghijklmnop',projectScope:'qrstuvwxyzABCDEF',mediaId}),...overrides});
const env=(bucket=new FakeBucket())=>({MEDIA_BUCKET:bucket,MEDIA_SIGNING_SECRET:'never returned secret',TELEGRAM_BOT_TOKEN:'bot token'});
const uploadRequest=(options:{origin?:string;auth?:boolean;projectId?:string;files?:Blob[];raw?:boolean}={})=>{const headers=new Headers();if(options.origin)headers.set('origin',options.origin);if(options.auth!==false)headers.set('X-Telegram-Init-Data','signed');if(options.raw)return new Request('https://app.test/api/media/passport-covers',{method:'POST',headers,body:'not multipart'});const form=new FormData();for(const file of options.files??[new Blob([structuralJPEG],{type:'image/jpeg'})])form.append('file',file,'cover.jpg');form.append('projectId',options.projectId??'project-123');return new Request('https://app.test/api/media/passport-covers',{method:'POST',headers,body:form});};
const bodyCode=async(response:Response)=>(await response.json() as any).code;

describe('Passport media diagnostics',()=>{
  it('reports configured identity and R2 list without exposing internals',async()=>{const bucket=new FakeBucket();const response=await handleMediaDiagnostics(env(bucket),deps());expect(response.status).toBe(200);expect(await response.json()).toEqual({ok:true,configured:true,identity:true,storageList:true});expect(bucket.lists).toEqual([{prefix:'passport-media/v1/',limit:1}]);});
  it('reports identity failure safely',async()=>{const response=await handleMediaDiagnostics(env(),deps({createIdentity:async()=>{throw new Error('secret detail')}}));expect(response.status).toBe(503);expect(await response.json()).toEqual({ok:false,configured:true,identity:false,storageList:false,code:'MEDIA_DIAGNOSTIC_IDENTITY'});});
  it('reports R2 list failure safely',async()=>{const bucket=new FakeBucket();bucket.fail='list';const response=await handleMediaDiagnostics(env(bucket),deps());expect(response.status).toBe(503);expect(await response.json()).toEqual({ok:false,configured:true,identity:true,storageList:false,code:'MEDIA_DIAGNOSTIC_STORAGE_LIST'});});
});

describe('Passport media upload route',()=>{
  it('requires Telegram auth',async()=>{const bucket=new FakeBucket();const response=await handleMediaUpload(uploadRequest({auth:false}),env(bucket),deps());expect(response.status).toBe(401);expect(await bodyCode(response)).toBe('TELEGRAM_AUTH_REQUIRED');expect(bucket.puts).toHaveLength(0)});
  it('rejects invalid Telegram auth',async()=>{const bucket=new FakeBucket();const response=await handleMediaUpload(uploadRequest(),env(bucket),deps({validateAuth:async()=>{throw new Error('bad')}}));expect(response.status).toBe(401);expect(await bodyCode(response)).toBe('TELEGRAM_AUTH_INVALID');expect(bucket.puts).toHaveLength(0)});
  it('rejects cross-origin before writing',async()=>{const bucket=new FakeBucket();const response=await handleMediaUpload(uploadRequest({origin:'https://evil.test'}),env(bucket),deps());expect(response.status).toBe(403);expect(await bodyCode(response)).toBe('CROSS_ORIGIN');expect(bucket.puts).toHaveLength(0)});
  it('rejects non-multipart',async()=>expect(await bodyCode(await handleMediaUpload(uploadRequest({raw:true}),env(),deps()))).toBe('MEDIA_INVALID_FORM'));
  it('fast-fails an oversized declared multipart body before R2 work',async()=>{const bucket=new FakeBucket();const request=new Request('https://app.test/api/media/passport-covers',{method:'POST',headers:{'X-Telegram-Init-Data':'signed','content-type':'multipart/form-data; boundary=x','content-length':String(4*1024*1024+1)},body:'x'});const response=await handleMediaUpload(request,env(bucket),deps());expect(response.status).toBe(413);expect(await bodyCode(response)).toBe('MEDIA_FILE_TOO_LARGE');expect(bucket.puts).toHaveLength(0);expect(bucket.lists).toHaveLength(0)});
  it('rejects multiple files',async()=>expect(await bodyCode(await handleMediaUpload(uploadRequest({files:[new Blob([structuralJPEG],{type:'image/jpeg'}),new Blob([structuralJPEG],{type:'image/jpeg'})]}),env(),deps()))).toBe('MEDIA_INVALID_FILE'));
  it('rejects non-JPEG MIME',async()=>expect(await bodyCode(await handleMediaUpload(uploadRequest({files:[new Blob([structuralJPEG],{type:'image/png'})]}),env(),deps()))).toBe('MEDIA_INVALID_TYPE'));
  it('rejects files over 3 MB',async()=>expect(await bodyCode(await handleMediaUpload(uploadRequest({files:[new Blob([new Uint8Array(3*1024*1024+1)],{type:'image/jpeg'})]}),env(),deps()))).toBe('MEDIA_FILE_TOO_LARGE'));
  it('rejects structurally invalid JPEG',async()=>expect(await bodyCode(await handleMediaUpload(uploadRequest({files:[new Blob([new Uint8Array([0xff,0xd8])],{type:'image/jpeg'})]}),env(),deps()))).toBe('MEDIA_INVALID_JPEG'));
  it.each(['../secret','a/b','with space','x'.repeat(129)])('rejects unsafe project id %j',async projectId=>expect(await bodyCode(await handleMediaUpload(uploadRequest({projectId}),env(),deps()))).toBe('MEDIA_INVALID_PROJECT'));
  it('writes exact key and safe metadata and returns only public fields',async()=>{const bucket=new FakeBucket();const response=await handleMediaUpload(uploadRequest(),env(bucket),deps());expect(response.status).toBe(201);expect(bucket.puts).toEqual([`passport-media/v1/${mediaId}.jpg`]);const stored=bucket.objects.get(bucket.puts[0])!;expect(stored.options.httpMetadata).toEqual({contentType:'image/jpeg',cacheControl:'public, max-age=31536000, immutable'});expect(stored.options.customMetadata).toMatchObject({ownerScope:'abcdefghijklmnop',projectScope:'qrstuvwxyzABCDEF',width:'3',height:'2'});expect(Object.keys(await response.json())).toEqual(['mediaId','contentType','bytes','width','height']);expect(bucket.lists).toEqual([{prefix:'passport-media/v1/m1_abcdefghijklmnop_',limit:101},{prefix:'passport-media/v1/m1_abcdefghijklmnop_qrstuvwxyzABCDEF_',limit:41}]);});
  it('enforces project quota without put',async()=>{const bucket=new FakeBucket();for(let i=0;i<40;i++)bucket.objects.set(`passport-media/v1/m1_abcdefghijklmnop_qrstuvwxyzABCDEF_${i}`,{bytes:new ArrayBuffer(0)});expect(await bodyCode(await handleMediaUpload(uploadRequest(),env(bucket),deps()))).toBe('MEDIA_PROJECT_QUOTA');expect(bucket.puts).toHaveLength(0)});
  it('enforces owner quota without put',async()=>{const bucket=new FakeBucket();for(let i=0;i<100;i++)bucket.objects.set(`passport-media/v1/m1_abcdefghijklmnop_otherScope0000_${i}`,{bytes:new ArrayBuffer(0)});expect(await bodyCode(await handleMediaUpload(uploadRequest(),env(bucket),deps()))).toBe('MEDIA_USER_QUOTA');expect(bucket.puts).toHaveLength(0)});
  it('has an isolated deterministic six-per-minute rate limit',async()=>{const bucket=new FakeBucket();let now=1000;const injected=deps({now:()=>now});for(let i=0;i<6;i++)expect((await handleMediaUpload(uploadRequest(),env(bucket),injected)).status).toBe(201);expect(await bodyCode(await handleMediaUpload(uploadRequest(),env(bucket),injected))).toBe('MEDIA_RATE_LIMIT');now+=60_001;expect((await handleMediaUpload(uploadRequest(),env(bucket),injected)).status).toBe(201)});
  it.each(['list','put'] as const)('maps %s failures to safe storage error',async fail=>{const bucket=new FakeBucket();bucket.fail=fail;const response=await handleMediaUpload(uploadRequest(),env(bucket),deps());expect(response.status).toBe(503);expect(await response.json()).toEqual({code:'MEDIA_STORAGE_ERROR',message:'Хранилище временно недоступно'})});
});

describe('public Passport media GET',()=>{
  it('returns safe 404 for invalid and missing ids',async()=>{expect(await bodyCode(await handleMediaGet('bad',env()))).toBe('MEDIA_NOT_FOUND');expect(await bodyCode(await handleMediaGet(mediaId,env()))).toBe('MEDIA_NOT_FOUND')});
  it('returns exact bytes and immutable headers without auth',async()=>{const bucket=new FakeBucket();bucket.objects.set(`passport-media/v1/${mediaId}.jpg`,{bytes:structuralJPEG.buffer.slice(0),etag:'"etag"'});const response=await handleMediaGet(mediaId,env(bucket));expect(response.status).toBe(200);expect(new Uint8Array(await response.arrayBuffer())).toEqual(structuralJPEG);expect(response.headers.get('content-type')).toBe('image/jpeg');expect(response.headers.get('cache-control')).toBe('public, max-age=31536000, immutable');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(response.headers.get('etag')).toBe('"etag"')});
  it('maps R2 get failure safely',async()=>{const bucket=new FakeBucket();bucket.fail='get';const response=await handleMediaGet(mediaId,env(bucket));expect(response.status).toBe(503);expect(await bodyCode(response)).toBe('MEDIA_STORAGE_ERROR')});
});
